export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_SUCCESSFUL = 'API_CALL_SUCCESSFUL';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const ADD_REQUESTS = 'ADD_REQUESTS';